### ISSUE TITLE
swagger Can not find package 

### ISSUE THREAD

**Issue by Kaign** [yvasiyarov/swagger#108]
HI, I tried to use swagger in example package:

```
$ pwd
/Users/Kaign/Documents/projects/GO/src/github.com/yvasiyarov/swagger/example

$ swagger -apiPackage="example" -mainApiFile="./web/main.go"
2016/02/06 15:31:31 Start parsing
2016/02/06 15:31:31 Can not find package example 
```

What am I doing wrong?

**Comment by ElliotReeve** [comment]
@Kaign I am getting the same, I want to use this but I can't get it to work for my API or for the example

**Comment by Kaign** [comment]
@ElliotReeve , looks like this project is abandoned, take a look at the https://github.com/go-swagger/go-swagger , it works fine

**Comment by RobertJGabriel** [comment]
@Kaign That repo is great, shame about this one, needed another admin :(

**Comment by boonep** [comment]
Are you guys using vendoring?  It looks like this project just checks the GOPATH.  @yvasiyarov can we confirm this is abandoned?  Thanks!

**Comment by boonep** [comment]
I was able to resolve my issues with vendoring using some quick hacks to the parse.go file.  The fixes work for my use case, but will almost definitely break others.  To view changes for your reference:  https://github.com/boonep/swagger/commit/450a060d76c51e6ebde26c77cf38643dacae205e

**Comment by dz0ny** [comment]
You can also use -ignore "github.com" -ignore "golang.org" to skip those paths while parsing

**Comment by samtech09** [comment]
I am getting similar issue. It was complaining about 
`2016/09/30 13:33:40 Start parsing
2016/09/30 13:33:41 Can not find package golang_org/x/net/lex/httplex 
`
Again i tried with `-ignore "github.com" -ignore "golang.org"` then it started giving following
`2016/09/30 13:36:34 Start parsing
2016/09/30 13:36:35 Can not find definition of object model. Current package dev/test/stapi/controllers
`
Is there any workaround?

**Comment by dselans** [comment]
Resurrecting this issue as I'm cleaning things up -- that's correct, this project attempts to find the pkg in question in the following order:

1. $GOPATH
2. $GOROOT/src
3. $GOROOT/src/pkg (go 1.4)

With a shortly upcoming PR (#137), the tool will also search for any dependency packages by looking for the pkg under `$CWD/vendor/*` and then `$GOPATH/$mainPkg/vendor/$dependency_package`.

So to make the example work, you'll have to do something along the lines of: `swagger -apiPackage="github.com/yvasiyarov/swagger/example" -mainApiFile=example/web/main.go -output=./API.md -format=markdown`. Or in other words, specify the full pkg name.
