### ISSUE TITLE
Not able to generate docs for my project which uses vendored packages

### ISSUE THREAD

**Issue by shtripat** [yvasiyarov/swagger#112]
I have a project which uses glide to download vendor packages. For example I use influxdb packages which get downloaded in "vendor" directory by glide tool.

For the same project when try generating REST docs using swagger, it does not find vendored packages. How can I make use of vendored packages for swagger as well?

**Comment by shtripat** [comment]
I dont see any update on this issue. Is there a way to use glide vendor packages for generating json using this package?

**Comment by mikunalpha** [comment]
At swagger/parser/parser.go #L118, change codes like this may help you.
```go
for _, path := range gopathsList {
  if evalutedPath, err := filepath.EvalSymlinks(filepath.Join("vendor", packagePath)); err == nil {
    if _, err := os.Stat(evalutedPath); err == nil {
      pkgRealpath = evalutedPath
      break
    }
  } else if evalutedPath, err := filepath.EvalSymlinks(filepath.Join(path, "src", packagePath)); err == nil {
    if _, err := os.Stat(evalutedPath); err == nil {
      pkgRealpath = evalutedPath
      break
    }
  }
}
```

**Comment by shtripat** [comment]
Oh that would be great help.
Will try this and update.

Regards,
Shubhendu

**Comment by plutov** [comment]
This PR will fix this issue - https://github.com/yvasiyarov/swagger/pull/115
