### ISSUE TITLE
Import Cycle

### ISSUE THREAD

**Issue by Jeevi21** [yvasiyarov/swagger#113]
Hi,
 when i try to install . I'm getting Import Cycle not allowed issue.

```
          `bash-4.1$ go get github.com/yvasiyarov/swagger
            import cycle not allowed
            package github.com/yvasiyarov/swagger
            imports flag
            imports errors
            imports runtime
            imports runtime/internal/atomic
            imports unsafe`
```

I tried downloading it manually as a zip and tried go install.. again the same issue.
Can someone help me out? I'm completely new to this(both swagger and go)

**Comment by dselans** [comment]
Is your `$GOPATH` and `$GOROOT` set correctly? It's possible that you also tried to `get` the project when master was unstable.
