### ISSUE TITLE
Not working on a gin-gonic project

### ISSUE THREAD

**Issue by landru29** [yvasiyarov/swagger#117]
When launching the command

`swagger -apiPackage=github.com/yy/xx -mainApiFile=main.go`

2016/09/01 18:44:04 Start parsing
2016/09/01 18:44:04 Can not find package context 

What is this package ? I do not use it in my project

**Comment by mikunalpha** [comment]
Some files of package golang.org/x/net/context will cause that message because they import context.

**Comment by leoswaldo** [comment]
you can use `-ignore "context"` in the command line
