### ISSUE TITLE
Plug-and-play instructions at README?

### ISSUE THREAD

**Issue by ppKrauss** [yvasiyarov/swagger#131]
I can help formating and adding step-by-step descriptions, but the "easy and dirirect" instructions exists?

PS: see also if this project solves [this classic problem](https://stackoverflow.com/questions/44803881/where-the-swagger-pretty-html-code/44804184#44804184)

**Comment by dselans** [comment]
I've updated the `README.md` which hopefully makes the tool a bit easier to use.

As for generating pretty HTML docs - this is currently unsupported but may get added in the future.
