### ISSUE TITLE
Can not find a package in GOROOT (Cloud9 IDE)

### ISSUE THREAD

**Issue by IvanRave** [yvasiyarov/swagger#53]
Cannot find system packages, like "io", "fmt" and others

In your code required packages verifies only in a "src" folder in GOROOT directory

    if evalutedPath, err := filepath.EvalSymlinks(filepath.Join(goroot, "src", packagePath)); err == nil {

https://github.com/yvasiyarov/swagger/blob/8274ce23174e03badaf457cbb57aecee74d49bf6/parser/parser.go#L127

in Cloud9 these packages stores in a $GOROOT/src/pkg/ folder (like /opt/go/src/pkg/fmt/..)

**Comment by IvanRave** [comment]
in Cloud9 by default: v1.2.1 of Go

>>Go 1.4 src/pkg → src

>>https://docs.google.com/document/d/12w7ksAXmo3sF1EWlbAp4adrm1kJoe_8WIFlaZshIHWM/edit

>>In April 2011, after a few months of discussion, we introduced $GOPATH to allow developers to work on code outside the standard tree. The form of a $GOPATH directory mimics the main repo, but because it’s all Go, we shortened src/pkg to src. The extra “pkg” element is a special case in the go command that makes the $GOROOT workspace different from the $GOPATH workspaces.

>>We propose to move all directories in $GOROOT/src/pkg to $GOROOT/src.

It will be good to add one more condition to your code (time-saving for Cloud9 developers)

**Comment by yvasiyarov** [comment]
@IvanRave can you, please, send a pull request with necessary changes ?

**Comment by IvanRave** [comment]
Maybe in the next month. Need to teach this stuff with forks and pull requests:)

**Comment by gregzuro** [comment]
I think that the code that I removed lately was -trying- to do what OP is asking.  I'll add it soon unless @IvanRave wants to do it.  Let me know.

**Comment by IvanRave** [comment]
@gregzuro fix it, please
