### ISSUE TITLE
Block model references

### ISSUE THREAD

**Issue by solher** [yvasiyarov/swagger#75]
Hi,
Is there a way to block the generation of related models ?
To allow my models to embed related ones, they all have references to each others.
So when I annotate my `Find` API method with `@Success 200 {object} domain.User`, in Swagger, it shows all the models of my app.

Thanks

**Comment by yvasiyarov** [comment]
Hello @solher, 
there is no way to do it.
Actually, you should not do it. If model embedded, your API clients must know about that model
