### ISSUE TITLE
How to set basePath?

### ISSUE THREAD

**Issue by zasran** [yvasiyarov/swagger#83]
Note: replaced the actual hostname by $host

It seems that the URL in 'Try it out!' is not set correctly and I don't see how to adjust it.

  - we host docs at: http://$host/doc/
  - in comments: // @SubApi User API [/user]
  - generated user/index.json has: "basePath": "{{.}}",

Which results in Try it out link like this: http://$host/doc//{{.}}/user/1

The correct link would be http://$host/user/1

I tried to manually change basePath in user/index.json to "/" and the try it out link looks correct now. Didn't fnd out how to change basePath. Tried @BasePath in comments both overall and for the specific API but it didn't help.

This might be more of a question than a bug, possibly something to add to docs (I did read all available docs as far as I can tell).

**Comment by solher** [comment]
Haha I actually knew there would be some questions about it someday as I didn't understand it myself at first.
The basePath is now set at {{.}} to allow templating (so a dynamic basePath at runtime).
It comes from the pull request https://github.com/yvasiyarov/swagger/pull/74.
Check out the example "web.go-example".

Maybe we should allow both dynamic and static basePath ? If the basePath is set by the flags, it is statically set in the jsons otherwise it is set {{.}}, ready to template. I don't know.

**Comment by zasran** [comment]
Not sure I fully understand it, one detail is why is the URL so strangely weird when basePath is {{.}} (there's doc there with two slashes which are not there if basePath is set to something). That's not the important question though.

More important question is how is it supposed to be used in general, we generate the docs (using swagger command) and then simply serve the file tree. The host is the host where it is served from so it's correct where ever we run it and the rest of the path is static (i.e. basePath is '/').

I see that web.go-example is doing the template interpolation but it seems  bit strange to require it. Is it really useful for pretty much everybody? I am totally new to swagger and Go swagger so maybe I am just doing it wrong? Once I found out about the basePath I was expecting it to be one of the declarative comments (something like // @BasePath /). Is that reasonable and simply nobody got around to implement it or does it sound unreasonable? Should we add the template interpolation?

Another question is about the specific template engine used, it seems from web.go-example that Go text/template is used. Wouldn't it make better sense to make output of swagger completely independent of Go? I mean it should be possible to host it by pretty much any web server (seems to me that's the Swagger idea).

Not sure this is the best forum for the discussion, let me know if there's a better one. Thanks!

**Comment by zasran** [comment]
Anybody?

Why is it that the result of swagger contains Go specific templates? Isn't the whole point of swagger that the documentation is generated and then served by HTTP server?

Can somebody explain the rationale and context? I would try to fix it (and submit pull request) but at the moment I don't know what the reasonable solution is and what the goals are...

**Comment by RobertJGabriel** [comment]
Im just throwing in my two cents , but it would almost be worth having both dynamic and static basePath. If someone is willing.
I do like the idea you have @zasran . As orignail it cause me some problems getting working on a live server :)

**Comment by zasran** [comment]
What are good places to specify basePath?

- swagger command line (i.e. when generating docs)
- main block of declarative comments (where ApiVersion etc. are)
- part of @SubApi comment
- each request declarative comment (seems to fine grained)

Swagger command ine seems like an obvious choise. It seems like each subApi can have its own basePath (it's in subApi index.json) so maybe @SubApi comment is also a good place?

Thoughts?

**Comment by RobertJGabriel** [comment]
What I have been doing it setting it in part of the @SubApi. So I think your spot on with setting it there but am open up to correction :) what do you think @solher

**Comment by solher** [comment]
The thing that we know for sure is that the templated basePath is and will stay a hack if we keep it.
As you say @zasran, the point of Swagger is normally to provide a standardized JSON to any HTTP server, not especially a Go one (and according to the Swagger spec, "The basePath does not support path templating").

That being said, it seems to me that it is current practice to serve the app documentation from the app itself (the default behavior of the generator is to generate Go files !) and it can be useful to inject the basePath at runtime (I use that feature).

I like the idea of using annotations like @SubApi to set that. I think info of the generated JSONs should be as much as possible in the annotations (it is the point after all).

But how did you implement it @RobertJGabriel ? In replacement of the current `// @SubApi User resource [/users]`, we now need to put `// @SubApi User resource [http://localhost:3000/api/users]` for example ?

**Comment by zasran** [comment]
So would it make sense to add:

- command line argument basePath (would be applied to all subApis)
- top level @BasePath declarative comment (also applied to all subApis)
- add basePath to top level declarative commet @SubApi

Any suggestions how to add basePath to @SubApi?

Current format: // @SubApi Description [URI]
With basePath: // @SubAi Description [basePath] [URI]

Doesn't look too good but not sure what else to do. If there is one element it would be URI, if there are two elements first one would be basePath and the second one URI.

Does it make sense to even have basePath per subApi? Can't one just add what would be basePath to URI and it would work the same? Or is it the case the basPath can have protocol/host/port and URI can be just path (docs say URI has to start with a slash '/')?
