### ISSUE TITLE
Parser Tests Failing

### ISSUE THREAD

**Issue by boonep** [yvasiyarov/swagger#87]
I attempted to run the go tests in the parser directory and I'm getting a lot of errors.  The first being:

```
./parser_test.go:40: cannot use IsController (type func(*ast.FuncDecl) bool) as type func(*ast.FuncDecl, string) bool in assignment
```

Should those be passing?  I wanted to fork and submit a pull request for adding base path parsing, but wanted to make sure all tests passed first.  Thanks!

**Comment by zasran** [comment]
The test is using a function with signature:

func IsController(funcDeclaration *ast.FuncDecl) bool

While parser and generator use:

func IsController(funcDeclaration *ast.FuncDecl, controllerClass string) bool

Should the generator's version of IsController be used in the test? Or are they different on purpose? The function signature obviously has to be fixed but the question is whether the bodies should be same or not (is it good to have two copies/version is this function? Should it be factored out?)

**Comment by dselans** [comment]
Parser tests have been fixed.
