### ISSUE TITLE
Doc generation does not take into account files inside of a package

### ISSUE THREAD

**Issue by rajeevsikka** [yvasiyarov/swagger#98]
Doc generation seems to work only for packages that are at the top level.
I have SubApis defined inside a file under a package. This is my source structure:
main.go
handler.go
packageFoo
|___ moreHandlers.go

Doc generation fails to take into account SubApi defined in moreHandlers.go

**Comment by gluk64** [comment]
You need to specify all packages explicitly, comma-separated:
> swagger -apiPackage="your/package/first,your/package/second"

**Comment by RanzBiswa** [comment]
This still doesn't works for me. 
My structure below:
-- subpackage
	->model.go
--web
	->main.go
api.go

How do I add all packages explicitly?

Can you give me in details?
